from sqlalchemy import Column, Integer, String, Text, ForeignKey, DateTime, JSON
from sqlalchemy.orm import relationship
from datetime import datetime
from backend.app.database.connection import Base

class Resume(Base):
    __tablename__ = "resumes"

    id = Column(Integer, primary_key=True, index=True)
    filename = Column(String, nullable=False)
    candidate_name = Column(String, nullable=True)
    summary = Column(Text, nullable=True)
    extracted_text = Column(Text, nullable=False)
    structured_data = Column(JSON, nullable=True) # Pydantic extraction of skills, experience, etc.
    created_at = Column(DateTime, default=datetime.utcnow)

    analyses = relationship("Analysis", back_populates="resume", cascade="all, delete-orphan")

class JobDescription(Base):
    __tablename__ = "job_descriptions"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=True)
    company = Column(String, nullable=True)
    full_text = Column(Text, nullable=False)
    structured_data = Column(JSON, nullable=True) # Pydantic extraction of requirements
    created_at = Column(DateTime, default=datetime.utcnow)

    analyses = relationship("Analysis", back_populates="job_description", cascade="all, delete-orphan")

class Analysis(Base):
    __tablename__ = "analyses"

    id = Column(String, primary_key=True, index=True) # UUID/String generated by backend
    resume_id = Column(Integer, ForeignKey("resumes.id", ondelete="CASCADE"), nullable=False)
    jd_id = Column(Integer, ForeignKey("job_descriptions.id", ondelete="CASCADE"), nullable=False)
    
    # Store the deterministic scores & RAG evaluations
    overall_score = Column(Integer, nullable=False)
    scores_breakdown = Column(JSON, nullable=False) # {required_skills, preferred_skills, semantic_match, experience, projects, ats, education}
    skills_analysis = Column(JSON, nullable=False) # {strong_matches: [], partial_matches: [], missing_skills: []}
    ats_analysis = Column(JSON, nullable=False) # {score, issues: []}
    recommendations = Column(JSON, nullable=False) # list of strings
    interview_questions = Column(JSON, nullable=False) # list of dicts/strings
    
    created_at = Column(DateTime, default=datetime.utcnow)

    resume = relationship("Resume", back_populates="analyses")
    job_description = relationship("JobDescription", back_populates="analyses")
